### ISSUE TITLE
Traceback in DailyModelUpdate

### ISSUE THREAD

**Issue by sjmf** [DurhamARC/ManyFEWS#88]
The following traceback occurs in DailyModelUpdate:

```
celery_1       | [2022-10-05 09:25:17,914: ERROR/ForkPoolWorker-3] Task calculations.dailyModelUpdate[08efd58f-f90c-4571-8690-179fa9c662a8] raised unexpected: ValueError('cannot reshape array of size 15 into shape (3,4)')
celery_1       | Traceback (most recent call last):
celery_1       |   File "/venv/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
celery_1       |     R = retval = fun(*args, **kwargs)
celery_1       |   File "/venv/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
celery_1       |     return self.run(*args, **kwargs)
celery_1       |   File "/app/calculations/tasks.py", line 186, in dailyModelUpdate
celery_1       |     runningGenerateRiverFlows(
celery_1       |   File "/app/calculations/generate_river_flows.py", line 518, in runningGenerateRiverFlows
celery_1       |     riverFlowsData = GenerateRiverFlows(
celery_1       |   File "/app/calculations/generate_river_flows.py", line 331, in GenerateRiverFlows
celery_1       |     np.array(TempMin).reshape((int(N / 4)), 4).min(axis=1)
celery_1       | ValueError: cannot reshape array of size 15 into shape (3,4)
```

However, the task succeeds. Logging here in the event that we see it again or it ends up being related to another issue.

**Comment by sjmf** [comment]
Closing as currently cannot reproduce.
